# Constants
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "Arcade Platformer"

CHARACTER_SCALING = 1
ENEMY_SCALING = 0.5
TILE_SCALING = 0.5
COIN_SCALING = 0.5
ENEMY_SCALING = 0.2

PLAYER_MOVEMENT_SPEED = 2
GRAVITY = 1
PLAYER_JUMP_SPEED = 16


LEFT_VIEWPORT_MARGIN = 350
RIGHT_VIEWPORT_MARGIN = 350
BOTTOM_VIEWPORT_MARGIN = 50
TOP_VIEWPORT_MARGIN = 100

# Player start position
PLAYER_START_X = 128 * TILE_SCALING * 2
PLAYER_START_Y = 128 * TILE_SCALING

RIGHT_FACING = 0
LEFT_FACING = 1

ENEMY_MAIN_PATH = "images/zombies/"
PLAYER_MAIN_PATH = "images/animated_characters/male_person/malePerson"
